### ISSUE TITLE
There was an error loading selected plots from the server.

### ISSUE THREAD

**Issue by mseidel42** [cms-DQM/CentralHDQM#30]
Hi,

I cannot see any plots at the moment, only the following error message:
```
There was an error loading selected plots from the server. Please try again later.
```

Best,
Markus

**Comment by mseidel42** [comment]
ping @andrius-k @jfernan2 

Still the same problem, in multiple browsers (Firefox, Chromium) :(

**Comment by jfernan2** [comment]
Thanks @intrepid42 
We are looking into it, apologies for the inconvenience

**Comment by andrius-k** [comment]
@intrepid42 indeed, sorry for the inconvenience!!! The problem seems to be related to the fact that the DB is "cold" and queries take longer than the timeout of the web server. 
If you experience said error message after the pre-loader in the button spins for a couple of seconds, try clicking *Submit* again. It might take a few tries but eventually the database will have cached your query and return the result.
We're currently working on a more proper solution to this problem.

**Comment by jfernan2** [comment]
@intrepid42 please let us know if your problems are gone to close this issue
Thanks

**Comment by mseidel42** [comment]
Hi Andrius, hi Javi, now it works! Thank you very much for fixing it :-)
